Ds 76 frontend admin dashboard (#15)
* Initial commit of early stages of the Admin Dashboard. Includes a reactive sidebar and searching for small to large displays.

* Added Dashboard UI Component and updated the Admin Dashboard.

* Added Network Activity Tab with Paginated Table data and analytics for API Calls.

* Added Network Activity Tab with Paginated Table data and analytics for API Calls.

* Updated the admin dashboard to preload the relative sidebar items display content.

* Added the roles and permissions UI to Admin Dashboard.

* Added some visual identication of where the mouse enters tabular rows.

* Add user dashboard with dummy data

* Added overlay for editing a users role. Need to fix user context.

* Fixed user contexts & role modification for users displayed in the table data. Also, refactored PaginatedTable to externally handle closing and opening operations.

* Fixed some eslint issues.

* cors fix

* Finished user dashboard UI (main parts)

* Eslint fix

* logout requirements & corsheaders

* ai management plus prediction system

so most of the ai management is done and the prediction system is almost done and needs to be tested

* flake 8 fixes

just fixing flake 8

* code fixes

* fix

* Added multi-filter and searching functionality to paginated table component. Also, partially created Account Recovery

* Fixed a bug where fetching data from states would not render on mount.

* Added discovery of dashboard components using the search bar. It creates a drop down filtering the query, clicking on a result opens the relative display.

* Added discovery of dashboard components using the search bar. It creates a drop down filtering the query, clicking on a result opens the relative display.

* Added heatmaps for checking accounts last logged in. Updated the package json with Chart JS library.

* Added some changes to the heatmap

* user amanagement + fixes

* Updated Recovery Analytics & Fixed an issue where scrolling does to the bottom of a page does not display all its content.

* Added the UI overlay for modifying account recovery.

* Missing debug IF

* Remove some dev code.

* SPAWN AS ADMIN

* Add token management on frontend, redirects and general fixes

* Eslint fix

* Added a container for creating new user accounts in Account Management/recovery

* roles, prediction system, permissions, and model management

while its not all ai related stuff the majority is

* Added a temporary solution for managing roles on account creation.

* Role check decorator

* Added audit logs

* Updated Models

* Adding dummy data jsons for the generation of rows in PostgreSQL

* Updated the SQL structure, please rebuild your project to reconfigure the database.

* Added all the dummy data for the JSON

* fixed linting errors for backend and frontend

* Start logging + Start creating dummy data + Permission checkers

* flake :)

* linted the database populator

* Relocated the JSON dummy data files.

* Refactored the backend database population to check for tables, create tables. and insert data accordingly. Also fixed OTP issues where an existing user is not checked for, which now uses emails and returns a status if a user exists already. Updated JSONS with improved data.

* Updated the populator to include error handling, and fixed invalid json payloads.

* Updated the column definitions in the populator to update to their correct type definitions. Also updated the datetime of users json.

* get_column_definitions -> OverflowError: signed integer is greater than maximum

* repository stuff

* linting errors

* linting errors

* linting errors

* linting errors

* Added docstrings to each endpoint, hooked up Roles & Permissions to use database information, and added some QoL systems.

* Added middleware for catching API requests and storing the user agent in the database of authenticated users.

* Added header authorisation tokens to protected endpoints on the repository layer. Additionally fixed an issue where new roles would not be displayed on the roles and permissions.

* linting

* Updated network activity lazy table loader to push onto a stack.

* Updated the models repo to add catboost

* Updated requirements file to add catboost and matplotlib

* Fixed a bug in RolePermissions where a roles permissions didnt locally update with the newly added permission.

* Fixed an issue on the backend where a role would not be deleted if RolePermissions entry was empty. Also fixed a bug where creating a new role would throw a permissions axios error.

* Fixed a bug where deleting a role didnt update the UI component, leaving the already deleted instance on the display.

* removed jsonresponse import

* Fixed an issue where deleting a role wouldnt remove the remainder state permissions.

* Updated the backend, and frontend to support monitoring of real data during API requests.

* linting errors

* function/monitoring/views.py:14:1: F811 redefinition of unused 'timezone' from line 5

* Fixed Account CRUD Recovery on the UI. Chart requires an update. Need admin_create_user fixed.

* updated models folder and moved prediction to container

* lint fix

* updated insurace json

* Update user dashboard UI

* Eslint fix

* Added the MLAAS UI

* linting

* loads of stuff claims and system rewrite

* tested and fixed

* flake stuff

* flake ignore

* final flake

* Updated the Populator Script to be fault tolerant to relational keys. Also added additional rows to the JSON population data to prevent invalid key types. Removed any association to previous SQL configurations.

* Connecting to backend

* Eslint fix

* Remove unused features

* Added Claims Handling, Finance Settlements, RBAC, and session listeners.

* bunch of stuff

* meric updating

* Add stripe

* QoL Changes & Stripe

* Forgot to remove this...

* Claims Handling - admin bulk update status

* pep8 linting

* pep8 linting

* pep8 linting

---------

Co-authored-by: levi-mate <135052941+levi-mate@users.noreply.github.com>
Co-authored-by: kanehill1999 <80599890+kanehill1999@users.noreply.github.com>
Co-authored-by: Prolicon <kiritotheillumatidorito@gmail.com>